[project]
name = "finance-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "plotly>=6.3.0",
    "requests>=2.32.5",
    "streamlit>=1.49.1",
    "tweepy>=4.16.0",
]
